### ISSUE TITLE
can't find include lib "compiler/src/v3_life.hrl"

### ISSUE THREAD

**Issue by Delitants** [sg2342/beam_disassemble#1]
===> Verifying dependencies...
===> Compiling beam_disassemble
===> Compiling src/x_beam_listing.erl failed
src/x_beam_listing.erl:24: can't find include lib "compiler/src/v3_life.hrl"

src/x_beam_listing.erl:79: record l undefined
src/x_beam_listing.erl:81: variable 'I' is unbound
src/x_beam_listing.erl:82: variable 'Vdb' is unbound
src/x_beam_listing.erl:84: variable 'Ke' is unbound

**Comment by sg2342** [comment]
compiler/src/v3_life.hrl is no longer present in  OTP21 or newer.
with OTP20 compilation will succeed but the resulting beam_disassemble will not work on beam files created with an OTP20 compiler.

The reason for this is that only features already present in OTP19 are supported.
I have no plans to change this, but feel free to fork and send PRs.

also: https://github.com/sg2342/beam_disassemble#limitations
